import type { Locale } from './i18n';

const en = {
  inventory: 'Stock management',
  skipToContent: 'Skip to content', uploadLimit: 'Choose up to 6 images at a time.',
  overview: 'Overview', products: 'Products', collections: 'Collections', orders: 'Orders', customers: 'Customers', content: 'Website content', stores: 'Stores', media: 'Media library', trash: 'Trash', settings: 'Settings',
  save: 'Save changes', cancel: 'Cancel', close: 'Close', edit: 'Edit', add: 'Add new', search: 'Search', all: 'All', remove: 'Remove', delete: 'Delete', moveToTrash: 'Move to Trash', confirm: 'Confirm', preview: 'Preview', back: 'Back', next: 'Next', previous: 'Previous',
  published: 'Published', draft: 'Draft', archived: 'Archived', status: 'Status', actions: 'Actions', name: 'Name', thai: 'Thai', english: 'English', image: 'Image', chooseDeviceImage: 'Select image from device', noImage: 'No image selected',
  empty: 'Nothing here yet', noResults: 'No matching results', clear: 'Clear filters', results: 'results', selected: 'selected', details: 'Details', required: 'Please complete all required fields.',
  saved: 'Changes saved in this demo.', demo: 'Presentation workspace', viewSite: 'View website', workspace: 'WORKSPACE', storeManagement: 'Store management',
  dashboardTitle: 'Your store, at a glance.', dashboardIntro: 'A clear view of your catalog, sample orders, and the work ahead.', goodMorning: 'WELCOME TO JJGLASS STUDIO', samplePeriod: 'September 2026 · Sample activity',
  sales: 'Sample sales', totalOrders: 'Sample orders', liveProducts: 'Published products', lowStock: 'Low stock', revenue: 'Sales overview', revenueNote: 'Illustrative daily sales from the sample orders', orderActivity: 'Recent orders', seeAll: 'View all',
  quickActions: 'Make something happen', quickIntro: 'The everyday tools for your store.', addProduct: 'Manage products', editWebsite: 'Edit website content', manageMedia: 'Manage your images',
  stockTitle: 'Inventory needs attention', stockNote: 'Products at or below your stock alert threshold.', inStock: 'in stock', allStockGood: 'Stock levels look good.', activityTitle: 'Workspace activity',
  demoData: 'DEMO DATA', overviewTip: 'Ready for your next presentation', overviewTipText: 'Explore an order, edit a product, or update a banner. Your changes stay in this browser until you reset the demo.',
  menu: 'Open navigation', dismiss: 'Dismiss message', localSaved: 'Saved in this browser', loading: 'Preparing your workspace…', storageError: 'Could not save. Browser storage may be full or unavailable. Your form is still open; remove unused uploaded images and try again.',
  recovery: 'Saved demo data could not be loaded. The original sample data is shown. Use Reset demo in Settings to start fresh.', storageUnavailable: 'Browser storage is unavailable. Enable local storage to save presentation changes.',
  imageSearch: 'Search image library', select: 'Select', none: 'None', demoAccount: 'Demo administrator', export: 'Export demo data', reset: 'Reset demo',
  resetTitle: 'Reset this presentation?', resetDescription: 'This removes the demo edits, Trash contents, and locally uploaded images in this browser and restores the original sample data.', resetDone: 'Original sample data restored.',
  productCount: 'products', orderCount: 'orders', customer: 'Customer', total: 'Total', date: 'Date', pending: 'Pending', processing: 'Processing', shipped: 'Shipped', completed: 'Completed', cancelled: 'Cancelled',
  libraryIntro: 'One place for the imagery behind your store.', upload: 'Add images', uploadHint: 'JPEG, PNG, or WebP · Up to 10 MB per file · Saved locally for this demo', uploading: 'Preparing images…',
  mediaOriginal: 'Site asset', mediaUploaded: 'Local upload', altText: 'Alternative text', fileName: 'File name', used: 'Used in this workspace', unused: 'Available', mediaDeleteTitle: 'Move this image to Trash?', mediaDeleteNote: 'The image can be restored from Trash for 30 days.',
  mediaInUse: 'This image is in use. Replace it in products, collections, content, or stores before deleting it.', uploadError: 'This image could not be prepared. Choose a valid JPEG, PNG, or WebP file under 10 MB.', uploadEmpty: 'Choose at least one image.',
  uploadPreview: 'Review images', uploadSave: 'Save to library', imageAdded: 'Images added to your demo library.', imageUpdated: 'Image details saved.', imageDeleted: 'Image moved to Trash.', download: 'Download',
  mediaCount: 'images', mediaTip: 'Select an image to edit its alternative text or see a larger preview.',
  trashHeadline: 'Restore within 30 days', trashIntro: 'Deleted products, website content, stores, and images stay here for 30 days. Restore an item before its time runs out.',
  trashRetention: 'Items are removed automatically after 30 days.', trashSearch: 'Search deleted items', trashAllTypes: 'All types',
  trashProducts: 'Products', trashContent: 'Website content', trashStores: 'Stores', trashMedia: 'Images',
  trashEmpty: 'Your trash is empty', trashEmptyNote: 'Deleted items will appear here for up to 30 days.', trashAddSample: 'Add sample item', trashSampleAdded: 'Sample deleted product added to Trash.',
  trashDeletedOn: 'Deleted', trashExpiresOn: 'Removed on', trashDaysLeft: 'days left', trashExpiresToday: 'Last day to restore',
  trashRestore: 'Restore', trashRestoreTitle: 'Restore this item?', trashRestoreNote: 'The item will return to its original section of the workspace.', trashExpired: 'Expired', trashDeleteForever: 'Delete permanently', trashDeleteTitle: 'Permanently delete this item?',
  trashDeleteNote: 'This removes the item from Trash immediately. You cannot restore it afterward.',
  trashRestored: 'Item restored from Trash.', trashDeletedForever: 'Item permanently deleted.',
  trashRestoreUnavailable: 'Could not restore this item. It may have expired or a current item uses the same identifier. Reload the workspace and check again.',
  trashDeleteUnavailable: 'Could not delete this item. Reload the workspace and check again.',
  staleData: 'Another tab changed this workspace. Your edit was not saved. Copy any unsaved form entries, then reload this tab before trying again.',
};
export type CmsCopyKey = keyof typeof en;
const th: Record<CmsCopyKey, string> = {
  inventory: 'จัดการสต็อก',
  skipToContent: 'ข้ามไปยังเนื้อหา', uploadLimit: 'เลือกรูปภาพได้ครั้งละไม่เกิน 6 รูป',
  overview: 'ภาพรวม', products: 'สินค้า', collections: 'หมวดหมู่และแบรนด์', orders: 'คำสั่งซื้อ', customers: 'ลูกค้า', content: 'เนื้อหาเว็บไซต์', stores: 'สาขา', media: 'คลังรูปภาพ', trash: 'ถังขยะ', settings: 'ตั้งค่า',
  save: 'บันทึกการเปลี่ยนแปลง', cancel: 'ยกเลิก', close: 'ปิด', edit: 'แก้ไข', add: 'เพิ่มใหม่', search: 'ค้นหา', all: 'ทั้งหมด', remove: 'นำออก', delete: 'ลบ', moveToTrash: 'ย้ายไปถังขยะ', confirm: 'ยืนยัน', preview: 'ดูตัวอย่าง', back: 'กลับ', next: 'ถัดไป', previous: 'ก่อนหน้า',
  published: 'เผยแพร่', draft: 'ฉบับร่าง', archived: 'เก็บถาวร', status: 'สถานะ', actions: 'จัดการ', name: 'ชื่อ', thai: 'ภาษาไทย', english: 'ภาษาอังกฤษ', image: 'รูปภาพ', chooseDeviceImage: 'เลือกรูปจากอุปกรณ์', noImage: 'ยังไม่ได้เลือกรูปภาพ',
  empty: 'ยังไม่มีข้อมูล', noResults: 'ไม่พบข้อมูลที่ตรงกัน', clear: 'ล้างตัวกรอง', results: 'รายการ', selected: 'เลือกแล้ว', details: 'รายละเอียด', required: 'กรุณากรอกข้อมูลที่จำเป็นให้ครบ',
  saved: 'บันทึกข้อมูลในตัวอย่างแล้ว', demo: 'พื้นที่สำหรับนำเสนอ', viewSite: 'ดูเว็บไซต์', workspace: 'พื้นที่ทำงาน', storeManagement: 'จัดการร้านค้า',
  dashboardTitle: 'ภาพรวมร้านของคุณ', dashboardIntro: 'ดูสินค้า คำสั่งซื้อตัวอย่าง และสิ่งที่ต้องจัดการในที่เดียว', goodMorning: 'ยินดีต้อนรับสู่ JJGLASS STUDIO', samplePeriod: 'กันยายน 2569 · ข้อมูลตัวอย่าง',
  sales: 'ยอดขายตัวอย่าง', totalOrders: 'คำสั่งซื้อตัวอย่าง', liveProducts: 'สินค้าที่เผยแพร่', lowStock: 'สินค้าใกล้หมด', revenue: 'ภาพรวมยอดขาย', revenueNote: 'ยอดขายรายวันจากคำสั่งซื้อตัวอย่าง', orderActivity: 'คำสั่งซื้อล่าสุด', seeAll: 'ดูทั้งหมด',
  quickActions: 'เริ่มจัดการร้านของคุณ', quickIntro: 'เครื่องมือที่ใช้ทุกวันสำหรับร้านค้า', addProduct: 'จัดการสินค้า', editWebsite: 'แก้ไขเนื้อหาเว็บไซต์', manageMedia: 'จัดการรูปภาพ',
  stockTitle: 'สต็อกที่ต้องดูแล', stockNote: 'สินค้าที่มีจำนวนต่ำกว่าหรือเท่ากับเกณฑ์แจ้งเตือน', inStock: 'ชิ้นในสต็อก', allStockGood: 'สต็อกสินค้าพร้อม', activityTitle: 'ความเคลื่อนไหวล่าสุด',
  demoData: 'ข้อมูลตัวอย่าง', overviewTip: 'พร้อมสำหรับการนำเสนอครั้งต่อไป', overviewTipText: 'ลองดูคำสั่งซื้อ แก้ไขสินค้า หรือเปลี่ยนแบนเนอร์ ข้อมูลจะอยู่ในเบราว์เซอร์นี้จนกว่าจะรีเซ็ต',
  menu: 'เปิดเมนู', dismiss: 'ปิดข้อความ', localSaved: 'บันทึกในเบราว์เซอร์นี้', loading: 'กำลังเตรียมพื้นที่ทำงาน…', storageError: 'บันทึกไม่ได้ พื้นที่เบราว์เซอร์อาจเต็มหรือถูกปิดใช้งาน ข้อมูลในฟอร์มยังอยู่ ลองลบรูปที่ไม่ได้ใช้แล้วบันทึกอีกครั้ง',
  recovery: 'โหลดข้อมูลตัวอย่างที่บันทึกไว้ไม่ได้ จึงแสดงข้อมูลเริ่มต้น ใช้รีเซ็ตตัวอย่างในหน้าตั้งค่าเพื่อเริ่มใหม่', storageUnavailable: 'ไม่สามารถใช้พื้นที่จัดเก็บของเบราว์เซอร์ได้ กรุณาเปิดใช้งานเพื่อบันทึกข้อมูลตัวอย่าง',
  imageSearch: 'ค้นหารูปภาพ', select: 'เลือก', none: 'ไม่มี', demoAccount: 'ผู้ดูแลระบบตัวอย่าง', export: 'ส่งออกข้อมูลตัวอย่าง', reset: 'รีเซ็ตตัวอย่าง',
  resetTitle: 'รีเซ็ตการนำเสนอนี้?', resetDescription: 'ลบการแก้ไข รายการในถังขยะ และรูปที่เพิ่มในเบราว์เซอร์นี้ แล้วคืนค่าข้อมูลตัวอย่างเริ่มต้น', resetDone: 'คืนค่าข้อมูลตัวอย่างแล้ว',
  productCount: 'สินค้า', orderCount: 'คำสั่งซื้อ', customer: 'ลูกค้า', total: 'ยอดรวม', date: 'วันที่', pending: 'รอดำเนินการ', processing: 'กำลังเตรียม', shipped: 'จัดส่งแล้ว', completed: 'สำเร็จ', cancelled: 'ยกเลิก',
  libraryIntro: 'รวมรูปภาพทั้งหมดที่ใช้ในร้านของคุณ', upload: 'เพิ่มรูปภาพ', uploadHint: 'JPEG, PNG หรือ WebP · ไม่เกิน 10 MB ต่อรูป · บันทึกในเบราว์เซอร์สำหรับตัวอย่างนี้', uploading: 'กำลังเตรียมรูปภาพ…',
  mediaOriginal: 'รูปจากเว็บไซต์', mediaUploaded: 'รูปที่เพิ่มในเครื่อง', altText: 'ข้อความอธิบายภาพ', fileName: 'ชื่อไฟล์', used: 'ใช้ในพื้นที่ทำงานนี้', unused: 'พร้อมใช้งาน', mediaDeleteTitle: 'ย้ายรูปภาพนี้ไปถังขยะ?', mediaDeleteNote: 'สามารถกู้คืนรูปภาพจากถังขยะได้ภายใน 30 วัน',
  mediaInUse: 'รูปนี้กำลังใช้งาน กรุณาเปลี่ยนรูปในสินค้า หมวดหมู่ เนื้อหา หรือสาขาก่อนลบ', uploadError: 'เตรียมรูปไม่ได้ กรุณาเลือกไฟล์ JPEG, PNG หรือ WebP ที่ถูกต้องและไม่เกิน 10 MB', uploadEmpty: 'กรุณาเลือกรูปอย่างน้อยหนึ่งรูป',
  uploadPreview: 'ตรวจสอบรูปภาพ', uploadSave: 'บันทึกในคลังรูปภาพ', imageAdded: 'เพิ่มรูปในคลังตัวอย่างแล้ว', imageUpdated: 'บันทึกรายละเอียดรูปแล้ว', imageDeleted: 'ย้ายรูปภาพไปถังขยะแล้ว', download: 'ดาวน์โหลด',
  mediaCount: 'รูปภาพ', mediaTip: 'เลือกรูปเพื่อแก้ไขข้อความอธิบายหรือดูตัวอย่างขนาดใหญ่',
  trashHeadline: 'กู้คืนได้ภายใน 30 วัน', trashIntro: 'สินค้า เนื้อหาเว็บไซต์ สาขา และรูปภาพที่ลบจะอยู่ที่นี่ 30 วัน กู้คืนก่อนครบกำหนด',
  trashRetention: 'รายการจะถูกลบโดยอัตโนมัติเมื่อครบ 30 วัน', trashSearch: 'ค้นหารายการที่ลบ', trashAllTypes: 'ทุกประเภท',
  trashProducts: 'สินค้า', trashContent: 'เนื้อหาเว็บไซต์', trashStores: 'สาขา', trashMedia: 'รูปภาพ',
  trashEmpty: 'ถังขยะว่างอยู่', trashEmptyNote: 'รายการที่ลบจะปรากฏที่นี่ไม่เกิน 30 วัน', trashAddSample: 'เพิ่มรายการตัวอย่าง', trashSampleAdded: 'เพิ่มสินค้าตัวอย่างในถังขยะแล้ว',
  trashDeletedOn: 'ลบเมื่อ', trashExpiresOn: 'ลบถาวรเมื่อ', trashDaysLeft: 'วันก่อนลบถาวร', trashExpiresToday: 'กู้คืนได้วันนี้เป็นวันสุดท้าย',
  trashRestore: 'กู้คืน', trashRestoreTitle: 'กู้คืนรายการนี้?', trashRestoreNote: 'รายการจะกลับไปยังส่วนเดิมในพื้นที่ทำงาน', trashExpired: 'ครบกำหนดแล้ว', trashDeleteForever: 'ลบถาวร', trashDeleteTitle: 'ลบรายการนี้ถาวร?',
  trashDeleteNote: 'รายการจะถูกนำออกจากถังขยะทันที และไม่สามารถกู้คืนได้อีก',
  trashRestored: 'กู้คืนรายการจากถังขยะแล้ว', trashDeletedForever: 'ลบรายการถาวรแล้ว',
  trashRestoreUnavailable: 'กู้คืนรายการนี้ไม่ได้ อาจครบกำหนดแล้วหรือมีรายการที่ใช้รหัสเดียวกันอยู่ กรุณาโหลดพื้นที่ทำงานใหม่แล้วตรวจสอบอีกครั้ง',
  trashDeleteUnavailable: 'ลบรายการนี้ไม่ได้ กรุณาโหลดพื้นที่ทำงานใหม่แล้วตรวจสอบอีกครั้ง',
  staleData: 'มีการแก้ไขพื้นที่ทำงานจากแท็บอื่น จึงยังไม่บันทึกการแก้ไขของคุณ คัดลอกข้อมูลที่ยังไม่บันทึกไว้ก่อน แล้วโหลดแท็บนี้ใหม่เพื่อลองอีกครั้ง',
};
export const cmsCopy: Record<Locale, Record<CmsCopyKey, string>> = { th, en };
