import type { Locale } from './i18n';

const en = {
  contentIntro: 'Shape the stories, pages, and imagery your customers discover.',
  page: 'Pages', banner: 'Homepage banners', story: 'Stories', catalog: 'Catalogs',
  newContent: 'Add content', editContent: 'Edit content', contentSearch: 'Search titles and content',
  title: 'Title', subtitle: 'Subtitle', body: 'Main content', destination: 'Button destination',
  destinationHint: 'Use a local path such as /en/products, or a complete https:// address.',
  contentType: 'Content type', image: 'Cover image', contentDetails: 'Content details',
  seo: 'Search appearance', seoHint: 'Preview how this content could appear in search. This demo does not publish changes.',
  seoTitle: 'SEO title', seoDescription: 'SEO description', titleHint: 'Use a clear title in both languages.',
  saveContent: 'Save content', contentSaved: 'Website content saved.', contentRemoved: 'Content moved to Trash.',
  invalidTitle: 'Enter a title in both Thai and English.', invalidUrl: 'Enter a valid http:// or https:// address, or a local path beginning with a single /.',
  previewTitle: 'CMS content preview', previewNote: 'Presentation preview · These edits are saved in the CMS demo only.',
  previewLanguage: 'Preview language', previewButton: 'Explore', backToEditor: 'Back to editor',
  untitled: 'Untitled content', noContent: 'Create your first content item', noContentHint: 'Add a page, homepage banner, story, or catalog to start shaping the website.',
  position: 'Position', moveUp: 'Move up', moveDown: 'Move down', bannerOrderSaved: 'Homepage banner order saved.',
  deleteContent: 'Move this content to Trash?', deleteContentNote: 'You can restore it for 30 days. The public website is unchanged.',
  storesIntro: 'Keep every location ready for customers to find and visit.', newStore: 'Add store', editStore: 'Edit store',
  storeSearch: 'Search store names and addresses', storeName: 'Store name', address: 'Address', hours: 'Opening hours',
  phone: 'Phone number', lineId: 'LINE ID', mapUrl: 'Map address', gallery: 'Store gallery', galleryHint: 'Choose images from your device. The first image is the cover.',
  addPhoto: 'Add gallery image', removePhoto: 'Remove image', duplicatePhoto: 'This image is already in the gallery. Choose a different image.', cover: 'Cover', photo: 'Photo',
  storeSaved: 'Store details saved.', storeRemoved: 'Store moved to Trash.',
  invalidStore: 'Enter a store name and address in both Thai and English.',
  storePreview: 'CMS store preview', openMap: 'Open map', noStores: 'Add your first store', noStoresHint: 'Add a location with its address, opening hours, and gallery.',
  deleteStore: 'Move this store to Trash?', deleteStoreNote: 'You can restore it for 30 days in this presentation workspace.',
  settingsIntro: 'The essentials behind your store, in one place.', general: 'Store identity', generalIntro: 'Contact details and a short introduction to JJGLASS.',
  siteName: 'Site name', email: 'Contact email', line: 'LINE account', description: 'Store description',
  delivery: 'Demo delivery rules', deliveryIntro: 'Illustrative settings for the presentation. Existing sample orders keep their recorded totals.',
  deliveryFee: 'Standard delivery fee (THB)', freeShipping: 'Free delivery from (THB)', freeShippingHint: 'Set to 0 for free delivery on every demo order.',
  inventory: 'Inventory alerts', inventoryIntro: 'Control which products appear in the dashboard low-stock list.', lowStockThreshold: 'Low-stock threshold',
  notifications: 'Notification preferences', notificationsIntro: 'Save your preferred workflow. This presentation does not send emails or notifications.',
  orderNotifications: 'New order notifications', orderNotificationsHint: 'Keep the team informed when a new order arrives.',
  lowStockNotifications: 'Low-stock notifications', lowStockNotificationsHint: 'Receive a reminder when stock reaches your threshold.',
  settingsSaved: 'Workspace settings saved.', invalidSettings: 'Enter a site name and a valid contact email.',
  invalidNumbers: 'Enter valid non-negative values. Delivery fee: up to 1,000,000; free-delivery threshold: up to 10,000,000; stock threshold: a whole number up to 100,000.',
  workspaceData: 'Presentation data', workspaceDataIntro: 'Export a copy of your demo, or restore the original sample data for your next meeting.',
  exportHint: 'Download the current workspace as a JSON file.', resetHint: 'Restore original sample data and remove this browser’s edits.',
  savedNotice: 'Saved in this browser.', changesOnly: 'Changes apply to this presentation workspace only.',
  noGallery: 'No gallery images selected', items: 'items', optional: 'Optional', saveError: 'The changes could not be saved. Your inputs have been kept; please try again.',
};
type ContentCopyKey = keyof typeof en;
const th: Record<ContentCopyKey, string> = {
  contentIntro: 'จัดการเรื่องราว หน้าเว็บไซต์ และภาพที่ลูกค้าจะได้พบ',
  page: 'หน้าเว็บไซต์', banner: 'แบนเนอร์หน้าแรก', story: 'บทความ', catalog: 'แคตตาล็อก',
  newContent: 'เพิ่มเนื้อหา', editContent: 'แก้ไขเนื้อหา', contentSearch: 'ค้นหาชื่อและเนื้อหา',
  title: 'หัวข้อ', subtitle: 'หัวข้อรอง', body: 'เนื้อหาหลัก', destination: 'ลิงก์ปลายทางของปุ่ม',
  destinationHint: 'ใช้เส้นทางในเว็บไซต์ เช่น /products หรือที่อยู่ https:// แบบเต็ม',
  contentType: 'ประเภทเนื้อหา', image: 'ภาพปก', contentDetails: 'รายละเอียดเนื้อหา',
  seo: 'การแสดงผลในการค้นหา', seoHint: 'ดูตัวอย่างการแสดงผลในหน้าค้นหา ตัวอย่างนี้ไม่เผยแพร่การเปลี่ยนแปลงจริง',
  seoTitle: 'ชื่อสำหรับการค้นหา', seoDescription: 'คำอธิบายสำหรับการค้นหา', titleHint: 'ใส่หัวข้อที่ชัดเจนทั้งภาษาไทยและภาษาอังกฤษ',
  saveContent: 'บันทึกเนื้อหา', contentSaved: 'บันทึกเนื้อหาเว็บไซต์แล้ว', contentRemoved: 'ย้ายเนื้อหาไปถังขยะแล้ว',
  invalidTitle: 'กรุณาใส่หัวข้อทั้งภาษาไทยและภาษาอังกฤษ', invalidUrl: 'กรุณาใส่ที่อยู่ http:// หรือ https:// ที่ถูกต้อง หรือเส้นทางในเว็บไซต์ที่เริ่มด้วย / เพียงตัวเดียว',
  previewTitle: 'ตัวอย่างเนื้อหาใน CMS', previewNote: 'ตัวอย่างสำหรับนำเสนอ · บันทึกการแก้ไขเฉพาะใน CMS ตัวอย่างเท่านั้น',
  previewLanguage: 'ภาษาตัวอย่าง', previewButton: 'ดูเพิ่มเติม', backToEditor: 'กลับไปแก้ไข',
  untitled: 'เนื้อหายังไม่มีชื่อ', noContent: 'สร้างเนื้อหาชิ้นแรกของคุณ', noContentHint: 'เพิ่มหน้าเว็บไซต์ แบนเนอร์ บทความ หรือแคตตาล็อกเพื่อเริ่มจัดการเว็บไซต์',
  position: 'ลำดับ', moveUp: 'เลื่อนขึ้น', moveDown: 'เลื่อนลง', bannerOrderSaved: 'บันทึกลำดับแบนเนอร์แล้ว',
  deleteContent: 'ย้ายเนื้อหานี้ไปถังขยะ?', deleteContentNote: 'คุณสามารถกู้คืนได้ภายใน 30 วัน เว็บไซต์สาธารณะไม่เปลี่ยนแปลง',
  storesIntro: 'อัปเดตข้อมูลทุกสาขาให้ลูกค้าค้นหาและแวะมาได้สะดวก', newStore: 'เพิ่มสาขา', editStore: 'แก้ไขสาขา',
  storeSearch: 'ค้นหาชื่อสาขาและที่อยู่', storeName: 'ชื่อสาขา', address: 'ที่อยู่', hours: 'เวลาเปิดทำการ',
  phone: 'หมายเลขโทรศัพท์', lineId: 'LINE ID', mapUrl: 'ลิงก์แผนที่', gallery: 'รูปภาพสาขา', galleryHint: 'เลือกรูปจากอุปกรณ์ รูปแรกจะใช้เป็นภาพปก',
  addPhoto: 'เพิ่มรูปภาพสาขา', removePhoto: 'นำรูปออก', duplicatePhoto: 'รูปนี้อยู่ในแกลเลอรีแล้ว กรุณาเลือกรูปอื่น', cover: 'ภาพปก', photo: 'รูปภาพ',
  storeSaved: 'บันทึกข้อมูลสาขาแล้ว', storeRemoved: 'ย้ายสาขาไปถังขยะแล้ว',
  invalidStore: 'กรุณาใส่ชื่อสาขาและที่อยู่ทั้งภาษาไทยและภาษาอังกฤษ',
  storePreview: 'ตัวอย่างสาขาใน CMS', openMap: 'เปิดแผนที่', noStores: 'เพิ่มสาขาแรกของคุณ', noStoresHint: 'เพิ่มสาขาพร้อมที่อยู่ เวลาเปิดทำการ และรูปภาพ',
  deleteStore: 'ย้ายสาขานี้ไปถังขยะ?', deleteStoreNote: 'คุณสามารถกู้คืนได้ภายใน 30 วันในพื้นที่นำเสนอนี้',
  settingsIntro: 'รวมข้อมูลสำคัญสำหรับร้านของคุณไว้ในที่เดียว', general: 'ข้อมูลร้าน', generalIntro: 'ข้อมูลติดต่อและคำแนะนำสั้น ๆ เกี่ยวกับ JJGLASS',
  siteName: 'ชื่อเว็บไซต์', email: 'อีเมลติดต่อ', line: 'บัญชี LINE', description: 'คำอธิบายร้าน',
  delivery: 'ค่าจัดส่งตัวอย่าง', deliveryIntro: 'การตั้งค่าสำหรับนำเสนอ คำสั่งซื้อตัวอย่างเดิมจะยังใช้ยอดรวมที่บันทึกไว้',
  deliveryFee: 'ค่าจัดส่งมาตรฐาน (บาท)', freeShipping: 'จัดส่งฟรีเมื่อซื้อครบ (บาท)', freeShippingHint: 'ใส่ 0 เพื่อจัดส่งฟรีสำหรับคำสั่งซื้อตัวอย่างทุกยอด',
  inventory: 'แจ้งเตือนสต็อก', inventoryIntro: 'กำหนดว่าสินค้าใดจะแสดงในรายการสินค้าใกล้หมดบนหน้าภาพรวม', lowStockThreshold: 'เกณฑ์สินค้าใกล้หมด',
  notifications: 'การแจ้งเตือน', notificationsIntro: 'บันทึกการตั้งค่าที่ต้องการ ตัวอย่างนี้ไม่ส่งอีเมลหรือการแจ้งเตือนจริง',
  orderNotifications: 'แจ้งเตือนคำสั่งซื้อใหม่', orderNotificationsHint: 'ให้ทีมทราบเมื่อมีคำสั่งซื้อใหม่',
  lowStockNotifications: 'แจ้งเตือนสินค้าใกล้หมด', lowStockNotificationsHint: 'แจ้งเตือนเมื่อสต็อกถึงเกณฑ์ที่กำหนด',
  settingsSaved: 'บันทึกการตั้งค่าแล้ว', invalidSettings: 'กรุณาใส่ชื่อเว็บไซต์และอีเมลติดต่อที่ถูกต้อง',
  invalidNumbers: 'กรุณาใส่ตัวเลขที่ไม่ติดลบ ค่าจัดส่งไม่เกิน 1,000,000 บาท ยอดจัดส่งฟรีไม่เกิน 10,000,000 บาท และเกณฑ์สต็อกเป็นจำนวนเต็มไม่เกิน 100,000',
  workspaceData: 'ข้อมูลการนำเสนอ', workspaceDataIntro: 'ส่งออกข้อมูลตัวอย่าง หรือคืนค่าข้อมูลเริ่มต้นสำหรับการนำเสนอครั้งต่อไป',
  exportHint: 'ดาวน์โหลดข้อมูลพื้นที่ทำงานปัจจุบันเป็นไฟล์ JSON', resetHint: 'คืนค่าข้อมูลตัวอย่างเริ่มต้นและลบการแก้ไขในเบราว์เซอร์นี้',
  savedNotice: 'บันทึกในเบราว์เซอร์นี้แล้ว', changesOnly: 'การเปลี่ยนแปลงมีผลเฉพาะในพื้นที่นำเสนอนี้',
  noGallery: 'ยังไม่ได้เลือกรูปสาขา', items: 'รายการ', optional: 'ไม่บังคับ', saveError: 'บันทึกการเปลี่ยนแปลงไม่ได้ ข้อมูลที่กรอกยังอยู่ กรุณาลองอีกครั้ง',
};
export const cmsContentCopy: Record<Locale, Record<ContentCopyKey, string>> = { th, en };
