import type { Locale } from './i18n';
import { MAX_PRODUCT_QUANTITY } from './pricing';

const en = {
  catalogEyebrow: 'YOUR PRODUCT CATALOG',
  title: 'Products, thoughtfully organised.',
  intro: 'Manage your glassware, pricing, and stock in one place.',
  addProduct: 'Add product',
  editProduct: 'Edit product',
  newProduct: 'New product',
  duplicateProduct: 'Duplicate product',
  duplicate: 'Duplicate',
  copySuffix: 'copy',
  archive: 'Archive',
  archiveProduct: 'Archive this product?',
  archiveProductNote: 'The product will remain in your catalog and order history. You can restore it by changing its status.',
  deleteProduct: 'Move this product to Trash?',
  deleteProductNote: 'The product moves to Trash for 30 days. Existing orders keep their recorded product details.',
  productSaved: 'Product saved in the demo catalog.',
  productArchived: 'Product archived.',
  productDeleted: 'Product moved to Trash.',
  productSearch: 'Search product name or SKU…',
  allCategories: 'All categories',
  allStatuses: 'All statuses',
  allInventory: 'All stock levels',
  publishedStockAlerts: 'Published stock alerts',
  category: 'Category',
  brand: 'Brand',
  product: 'Product',
  sku: 'SKU',
  price: 'Price',
  priceLabel: 'Price (THB)',
  priceRange: 'Unit price range',
  quantityPricing: 'Quantity pricing',
  quantityPricingHint: 'Set a lower unit price when a customer buys more of the same product.',
  minimumQuantity: 'Minimum quantity',
  unitPrice: 'Unit price (THB)',
  addPriceTier: 'Add price tier',
  removePriceTier: 'Remove tier',
  noPriceTiers: 'No quantity discounts yet. The base price applies to every quantity.',
  stock: 'Stock',
  stockLabel: 'Available stock',
  units: 'units',
  featured: 'Featured',
  featuredHint: 'Highlight this product in your demo selection.',
  productInfo: 'Product information',
  organisation: 'Organisation & inventory',
  description: 'Description',
  capacity: 'Capacity / size',
  capacityHint: 'For example, 350 ml',
  chooseCategory: 'Select a category',
  chooseBrand: 'Select a brand',
  noProducts: 'Your next collection starts here.',
  noProductsHint: 'Add a product with its image, bilingual details, and price.',
  noResultsHint: 'Try a different search or clear the filters.',
  nameRequired: 'Enter a product name in both Thai and English.',
  skuRequired: 'Enter a SKU for this product.',
  duplicateSku: 'This SKU is already used. Choose a unique SKU.',
  priceInvalid: 'Enter a price greater than zero.',
  tierQuantityInvalid: `Each minimum quantity must be a unique whole number from 2 to ${MAX_PRODUCT_QUANTITY.toLocaleString('en-US')}, in ascending order.`,
  tierPriceInvalid: 'Each quantity price must be greater than zero and lower than the price before it.',
  stockInvalid: 'Stock must be a whole number of zero or more.',
  categoryRequired: 'Select an available category.',
  brandRequired: 'Select an available brand.',
  imageRequired: 'Choose a product image.',
  chooseFromDevice: 'Choose image from device',
  deviceImageHint: 'JPEG, PNG, or WebP up to 10 MB. Preview it here; it is saved with the product.',
  preparingImage: 'Preparing image preview…',
  imageReady: 'Ready to save',
  archivedSelection: 'Archived',
  productCount: 'Products',
  publishedCount: 'Published',
  stockAlerts: 'Stock alerts',
  zeroStock: 'Out of stock',
  lowStock: 'Low stock',
  collectionEyebrow: 'A PLACE FOR EVERYTHING',
  collectionTitle: 'Curate your collections.',
  collectionIntro: 'Keep categories and brands easy to browse, with images that tell their story.',
  categories: 'Categories',
  brands: 'Brands',
  addCategory: 'Add category',
  addBrand: 'Add brand',
  editCategory: 'Edit category',
  editBrand: 'Edit brand',
  categorySaved: 'Category saved.',
  brandSaved: 'Brand saved.',
  categoryArchived: 'Category archived.',
  brandArchived: 'Brand archived.',
  categoryNameRequired: 'Enter a category name in both Thai and English.',
  brandNameRequired: 'Enter a brand name.',
  duplicateCategory: 'A category with this name already exists.',
  duplicateBrand: 'A brand with this name already exists.',
  brandName: 'Brand name',
  brandNameHint: 'The official brand name is shared across both languages.',
  collectionSearch: 'Search collections…',
  collectionArchive: 'Archive this collection?',
  collectionArchiveNote: 'Existing product relationships are kept. This collection will no longer be available for new products until restored.',
  linkedProducts: 'Linked products',
  noCategories: 'No categories yet',
  noBrands: 'No brands yet',
  collectionEmptyHint: 'Add a name and a cover image to create a collection.',
  collectionImage: 'Collection cover image',
  optional: 'Optional',
  resultCount: 'Showing {from}–{to} of {count} products',
  collectionCount: '{count} collections',
};
export type CmsProductsCopyKey = keyof typeof en;
const th: Record<CmsProductsCopyKey, string> = {
  catalogEyebrow: 'แคตตาล็อกสินค้าของคุณ',
  title: 'จัดการสินค้าทุกชิ้นอย่างเป็นระเบียบ',
  intro: 'ดูแลเครื่องแก้ว ราคา และสต็อกสินค้าได้ในที่เดียว',
  addProduct: 'เพิ่มสินค้า',
  editProduct: 'แก้ไขสินค้า',
  newProduct: 'สินค้าใหม่',
  duplicateProduct: 'ทำสำเนาสินค้า',
  duplicate: 'ทำสำเนา',
  copySuffix: 'สำเนา',
  archive: 'เก็บถาวร',
  archiveProduct: 'เก็บสินค้านี้ถาวร?',
  archiveProductNote: 'สินค้ายังคงอยู่ในแคตตาล็อกและประวัติคำสั่งซื้อ คุณสามารถเรียกคืนได้โดยเปลี่ยนสถานะ',
  deleteProduct: 'ย้ายสินค้านี้ไปถังขยะ?',
  deleteProductNote: 'สินค้านี้จะอยู่ในถังขยะ 30 วัน โดยคำสั่งซื้อเดิมยังคงรายละเอียดสินค้าที่บันทึกไว้',
  productSaved: 'บันทึกสินค้าในแคตตาล็อกตัวอย่างแล้ว',
  productArchived: 'เก็บสินค้าถาวรแล้ว',
  productDeleted: 'ย้ายสินค้าไปถังขยะแล้ว',
  productSearch: 'ค้นหาชื่อสินค้าหรือรหัส SKU…',
  allCategories: 'ทุกหมวดหมู่',
  allStatuses: 'ทุกสถานะ',
  allInventory: 'ทุกระดับสต็อก',
  publishedStockAlerts: 'แจ้งเตือนสต็อกสินค้าที่เผยแพร่',
  category: 'หมวดหมู่',
  brand: 'แบรนด์',
  product: 'สินค้า',
  sku: 'รหัส SKU',
  price: 'ราคา',
  priceLabel: 'ราคา (บาท)',
  priceRange: 'ช่วงราคาต่อชิ้น',
  quantityPricing: 'ราคาตามจำนวน',
  quantityPricingHint: 'กำหนดราคาต่อชิ้นให้ลดลง เมื่อลูกค้าซื้อสินค้าชนิดเดียวกันในจำนวนที่มากขึ้น',
  minimumQuantity: 'จำนวนขั้นต่ำ',
  unitPrice: 'ราคาต่อชิ้น (บาท)',
  addPriceTier: 'เพิ่มระดับราคา',
  removePriceTier: 'ลบระดับราคา',
  noPriceTiers: 'ยังไม่มีส่วนลดตามจำนวน ราคาปกติจะใช้กับทุกจำนวน',
  stock: 'สต็อก',
  stockLabel: 'จำนวนสินค้าพร้อมขาย',
  units: 'ชิ้น',
  featured: 'สินค้าแนะนำ',
  featuredHint: 'เลือกสินค้านี้เป็นสินค้าแนะนำในตัวอย่าง',
  productInfo: 'ข้อมูลสินค้า',
  organisation: 'หมวดหมู่และสต็อก',
  description: 'รายละเอียด',
  capacity: 'ความจุ / ขนาด',
  capacityHint: 'เช่น 350 มล.',
  chooseCategory: 'เลือกหมวดหมู่',
  chooseBrand: 'เลือกแบรนด์',
  noProducts: 'เริ่มคอลเลกชันใหม่ของคุณที่นี่',
  noProductsHint: 'เพิ่มสินค้าพร้อมรูป ข้อมูลสองภาษา และราคา',
  noResultsHint: 'ลองเปลี่ยนคำค้นหาหรือล้างตัวกรอง',
  nameRequired: 'กรุณากรอกชื่อสินค้าทั้งภาษาไทยและภาษาอังกฤษ',
  skuRequired: 'กรุณากรอกรหัส SKU ของสินค้า',
  duplicateSku: 'มีรหัส SKU นี้แล้ว กรุณาใช้รหัสอื่น',
  priceInvalid: 'กรุณากรอกราคาที่มากกว่าศูนย์',
  tierQuantityInvalid: `จำนวนขั้นต่ำแต่ละระดับต้องเป็นจำนวนเต็มไม่ซ้ำกัน ตั้งแต่ 2–${MAX_PRODUCT_QUANTITY.toLocaleString('en-US')} และเรียงจากน้อยไปมาก`,
  tierPriceInvalid: 'ราคาแต่ละระดับต้องมากกว่าศูนย์และต่ำกว่าระดับก่อนหน้า',
  stockInvalid: 'จำนวนสต็อกต้องเป็นจำนวนเต็มตั้งแต่ศูนย์ขึ้นไป',
  categoryRequired: 'กรุณาเลือกหมวดหมู่ที่พร้อมใช้งาน',
  brandRequired: 'กรุณาเลือกแบรนด์ที่พร้อมใช้งาน',
  imageRequired: 'กรุณาเลือกรูปสินค้า',
  chooseFromDevice: 'เลือกรูปจากอุปกรณ์',
  deviceImageHint: 'ไฟล์ JPEG, PNG หรือ WebP ไม่เกิน 10 MB ดูตัวอย่างได้ที่นี่ และบันทึกพร้อมสินค้า',
  preparingImage: 'กำลังเตรียมภาพตัวอย่าง…',
  imageReady: 'พร้อมบันทึก',
  archivedSelection: 'เก็บถาวร',
  productCount: 'สินค้าทั้งหมด',
  publishedCount: 'เผยแพร่แล้ว',
  stockAlerts: 'แจ้งเตือนสต็อก',
  zeroStock: 'สินค้าหมด',
  lowStock: 'สินค้าใกล้หมด',
  collectionEyebrow: 'จัดหมวดหมู่ให้น่าค้นหา',
  collectionTitle: 'ดูแลหมวดหมู่และแบรนด์ของคุณ',
  collectionIntro: 'จัดหมวดหมู่และแบรนด์ให้ค้นหาง่าย พร้อมรูปภาพที่สื่อถึงแต่ละคอลเลกชัน',
  categories: 'หมวดหมู่',
  brands: 'แบรนด์',
  addCategory: 'เพิ่มหมวดหมู่',
  addBrand: 'เพิ่มแบรนด์',
  editCategory: 'แก้ไขหมวดหมู่',
  editBrand: 'แก้ไขแบรนด์',
  categorySaved: 'บันทึกหมวดหมู่แล้ว',
  brandSaved: 'บันทึกแบรนด์แล้ว',
  categoryArchived: 'เก็บหมวดหมู่ถาวรแล้ว',
  brandArchived: 'เก็บแบรนด์ถาวรแล้ว',
  categoryNameRequired: 'กรุณากรอกชื่อหมวดหมู่ทั้งภาษาไทยและภาษาอังกฤษ',
  brandNameRequired: 'กรุณากรอกชื่อแบรนด์',
  duplicateCategory: 'มีหมวดหมู่ชื่อนี้แล้ว',
  duplicateBrand: 'มีแบรนด์ชื่อนี้แล้ว',
  brandName: 'ชื่อแบรนด์',
  brandNameHint: 'ชื่อทางการของแบรนด์ใช้ร่วมกันทั้งสองภาษา',
  collectionSearch: 'ค้นหาหมวดหมู่และแบรนด์…',
  collectionArchive: 'เก็บคอลเลกชันนี้ถาวร?',
  collectionArchiveNote: 'สินค้าที่เชื่อมโยงยังคงอยู่ แต่จะไม่สามารถเลือกคอลเลกชันนี้ให้สินค้าใหม่ได้จนกว่าจะเรียกคืน',
  linkedProducts: 'สินค้าที่เชื่อมโยง',
  noCategories: 'ยังไม่มีหมวดหมู่',
  noBrands: 'ยังไม่มีแบรนด์',
  collectionEmptyHint: 'เพิ่มชื่อและรูปปกเพื่อสร้างคอลเลกชัน',
  collectionImage: 'รูปปกคอลเลกชัน',
  optional: 'ไม่บังคับ',
  resultCount: 'แสดง {from}–{to} จาก {count} สินค้า',
  collectionCount: '{count} คอลเลกชัน',
};

export const cmsProductsCopy: Record<Locale, Record<CmsProductsCopyKey, string>> = { th, en };
